### ISSUE TITLE
--align-text should set_search after set_alignment_fsg

### ISSUE THREAD

**Issue by lenzo-duo** [ReadAlongs/SoundSwallower#18]
Detail:

```
(.env) Hobbes:build kal$ soundswallower --model /Volumes/experiments/en-es/en/phonetic-1000/model_parameters/en-lss-02.cd_ptm_1000 --dict  /Volumes/experiments/en-es/en/etc/en-lss-02.dic --align-text "i am good thank you" ~/wav/i_am_good_thank_you.wav 
INFO:root:Setting sample rate to 24000
INFO:root:Increasing FFT size to 1024 for sample rate 24000
ERROR: "pocketsphinx.c", line 594: No search module is selected, did you forget to specify a language model or grammar?
Traceback (most recent call last):
  File "/Users/kal/dev/other/SoundSwallower/.env/bin/soundswallower", line 33, in <module>
    sys.exit(load_entry_point('soundswallower', 'console_scripts', 'soundswallower')())
  File "/Users/kal/dev/other/SoundSwallower/py/soundswallower/cli.py", line 152, in main
    _, file_align = decoder.decode_file(input_file)
  File "_soundswallower.pyx", line 732, in _soundswallower.Decoder.decode_file
    self.start_utt()
  File "_soundswallower.pyx", line 413, in _soundswallower.Decoder.start_utt
    raise RuntimeError, "Failed to start utterance processing"
RuntimeError: Failed to start utterance processing

```

However when using a JSGF, it does fine:

```
$ soundswallower --model /Volumes/experiments/en-es/en/phonetic-1000/model_parameters/en-lss-02.cd_ptm_1000 --dict  /Volumes/experiments/en-es/en/etc/en-lss-02.dic ~/wav/i_am_good_thank_you.wav -g i_am_good_thank_you.jsgf 
INFO:root:Setting sample rate to 24000
INFO:root:Increasing FFT size to 1024 for sample rate 24000
[[{"id": "i", "start": 0.0, "end": 0.2}, {"id": "am", "start": 0.2, "end": 0.37}, {"id": "good", "start": 0.37, "end": 0.75}, {"id": "thank", "start": 0.75, "end": 1.18}, {"id": "you", "start": 1.18, "end": 1.46}]]

```

**Comment by dhdaines** [comment]
Hmm, there is something else going on here, because set_search no longer exists, strictly speaking.  I think it is an interaction between the `--model` and `--dict` arguments and `--align-text`.  Looking into it now...

**Comment by dhdaines** [comment]
Actually the issue is the code to automatically increase `-nfft` depending on `-samprate` is calling ps_reinit() which wipes out any FSG that has been loaded programmatically, as is the case with --align-text.  Thanks for finding this problem, I will fix it for the next release, which will be soon.

It's actually quite broken, so for the time being you will need to downsample the input :(
