### ISSUE TITLE
Python build fails on ARM cpu

### ISSUE THREAD

**Issue by zavalyshyn** [ReadAlongs/SoundSwallower#33]
Hi,

I'm trying to build a Python package on an Arm board (Raspberry Pi 3b) but it keeps failing with the below error.
Any idea how I can debug it and try to solve it? Thanks

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/zavalyshyn/SoundSwallower
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: soundswallower
  Building wheel for soundswallower (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpwtugxr1s_in_process.py build_wheel /tmp/tmpnzbnnqdm
       cwd: /tmp/pip-req-build-1cursi7w
  Complete output (56 lines):
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-1cursi7w/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Traceback (most recent call last):
    File "/tmp/tmpwtugxr1s_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpwtugxr1s_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpwtugxr1s_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-c4y_864f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-c4y_864f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-c4y_864f/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(code, locals())
    File "<string>", line 4, in <module>
    File "/tmp/pip-build-env-c4y_864f/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 632, in setup
      env = cmkr.configure(
    File "/tmp/pip-build-env-c4y_864f/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 302, in configure
      cmd.append(f"{prefix}_NumPy_INCLUDE_DIRS:PATH=" + np.get_include())
  AttributeError: module 'numpy' has no attribute 'get_include'
  ----------------------------------------
  ERROR: Failed building wheel for soundswallower
Failed to build soundswallower
ERROR: Could not build wheels for soundswallower which use PEP 517 and cannot be installed directly
```

**Comment by zavalyshyn** [comment]
I'm terribly sorry. The issue resolved itself. I don't remember exactly how I fixed it but I think the trick was installing good old missing dependency libraries and updating my pip version.

Sorry for a false alarm and thanks for your hard work on Soundswallower
